@host = http://localhost:4004


GET {{host}}/oms/Products?$orderby=ID
Authorization: Basic admin:admin




###
GET {{host}}/oms/Customers?$orderby=ID&$select=modifiedBy, createdBy
Authorization: Basic admin:admin

###
POST {{host}}/oms/Orders
Content-Type: application/json
Authorization: Basic admin:admin

{
    "customer_ID": "195229a4-7783-4ce0-839d-f576e1813230",
    "items": [
        {
            "product_ID": "4f112801-8b66-410a-a595-0f964ba2f14f",
            "quantity": 10
        } 
    ]
}

###

GET {{host}}/oms/Orders?$count=true&$expand=items
Authorization: Basic admin:admin

###
POST {{host}}/oms/Orders(9b6ad5cb-342a-4a55-a163-c3d08f478b08)/cancel

###
GET {{host}}/oms/OrderSummary

###
POST {{host}}/oms/Products
Content-Type: application/json
Authorization: Basic alice:alice

{
    "name": "Radio",
    "price": 412.98,
    "stock": 140,
    "category": "HUAWEI"

}

###
GET {{host}}/oms/Products(9b6ad5cb-342a-4a55-a163-c3d08f478b08, IsActiveEntity=true)

###
PATCH {{host}}/oms/Products(0d72474d-65e5-4fe3-a68c-e8216ae54799, IsActiveEntity=true)
Content-Type: application/json

{ "name": "xxx"}

###
GET {{host}}/oms/Customers
Authorization: Basic alice:alice

###     
POST {{host}}/oms/Customers
Content-Type: application/json
Authorization: Basic alice:alice


{"name": "Jean", "phone": "+25078709334", "email": "jean@sample.com"}

