@host = http://localhost:4004


GET {{host}}/oms/Products?$orderby=ID



###
GET {{host}}/oms/Customers?$orderby=ID&$select=modifiedBy, createdBy###
POST {{host}}/oms/Orders
Content-Type: application/json

{
    "customer_ID": "195229a4-7783-4ce0-839d-f576e1813230",
    "items": [
        {
            "product_ID": "966a53ac-1379-4a97-b119-3b6da2c49f8b",
            "quantity": 1
        } 
    ]
}

###

GET {{host}}/oms/Orders?$count=true


###
POST {{host}}/oms/Orders(9b6ad5cb-342a-4a55-a163-c3d08f478b08)/cancel

###
GET {{host}}/oms/OrderSummary

###
POST {{host}}/oms/Products
Content-Type: application/json
Authorization: Basic alice:alice

{
    "name": "Radio",
    "price": 412.98,
    "stock": 140,
    "category": "HUAWEI"

}