/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("OrderSummaryListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheOrderSummaryList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheOrderSummaryList.onFilterBar().iCheckFilterField("Status");
            Then.onTheOrderSummaryList.onFilterBar().iCheckFilterField("Customer");
            Then.onTheOrderSummaryList.onFilterBar().iCheckFilterField("Order Date");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheOrderSummaryList.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheOrderSummaryList.onFilterBar().iExecuteSearch();
        //     Then.onTheOrderSummaryList.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheOrderSummaryList.onTable().iCheckColumns(undefined, {"customerName":{"header":"Customer"},"createdAt":{"header":"Order Date"},"totalPrice":{"header":"Revenue"},"orderCount":{"header":"Order Count"},"status":{"header":"Status"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheOrderSummaryList.onFilterBar().iExecuteSearch();
            
            Then.onTheOrderSummaryList.onTable().iCheckRows();

            When.onTheOrderSummaryList.onTable().iPressRow(0);
            Then.onTheOrderSummaryObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});